# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709643168959b8f5587c2d450956be1b05a6edd1e41e0b905817777744e6bf947f0087241aa0cceb0b4ddb240e492a79b29bbf137c3b9c4820a0d5d0a044e1e2

test:
  secret_key_base: f07f7480ecde91d98d88ea9cd65b7b0946d8304aaee60325480f6f4a730f7f0be7cd8f8073903172340507bb6f93764c5fcb35ba2143bd06822ff8cc4ea7dda4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
